package com.example.mitension

import android.content.Context

/** Static resource references keep translated strings visible to lint and resource shrinking. */
private val textResources = mapOf(
    "Imprimir" to R.string.s_ead3a493,
    "Formato del archivo" to R.string.s_1afbfccf,
    "Columnas" to R.string.s_deb1c628,
    "Usa el Excel (.xlsx) exportado por Mi Tensión como plantilla. Conserva la primera fila y el orden de las columnas; no uses fórmulas." to R.string.s_a69b6ee9,
    "Cada fila desde la segunda es una toma independiente. Puedes importar 1, 2 o 3 tomas de mañana o noche por día; no se promedian ni se exige completar tres." to R.string.s_16d098e2,
    "Mañana y noche se calculan por la fecha y hora local: antes de las 14:00 es mañana; desde las 14:00 es noche. La columna B no cambia esa clasificación." to R.string.s_e993def4,
    "A, C, D y G son obligatorias. A debe ser una fecha y hora de Excel, no texto; C y D son números enteros sin unidades. E, F y H pueden quedar vacías." to R.string.s_f955df66,
    "G identifica cada toma: conserva su UUID para evitar duplicados y usa un UUID distinto para una toma nueva. I, J y K son columnas técnicas ocultas; no las modifiques ni copies sus valores a tomas nuevas." to R.string.s_3526c142,
    "Pellizca o toca dos veces para ampliar." to R.string.s_d9dc4ecc,
    "Toca para ampliar la imagen." to R.string.s_d4b1d477,
    "Importar registros de Excel" to R.string.s_4d5c2d62,
    "Selecciona un archivo Excel exportado por Mi Tensión. Se añaden los registros nuevos sin borrar tu histórico ni duplicar tomas." to R.string.s_bd37a5c3,
    "No se pudo importar el Excel. Usa un archivo exportado por Mi Tensión con registros válidos." to R.string.s_d8215a28,
    "Segundos avisos programados: %ld" to R.string.s_ef3d37a3,
    "Han pasado 30 minutos y no has guardado la toma de este periodo. Regístrala cuando puedas." to R.string.s_7ba6fa8a,
    "No se pudo actualizar el segundo aviso. Revisa los permisos de notificaciones y vuelve a abrir Alertas." to R.string.s_6afcd43b,
    "Si no guardas una toma de ese día y periodo, recibirás una segunda notificación con sonido 30 minutos después. Solo se repite una vez. Se preparan los próximos 21 días y se renuevan al abrir la app; abre Mi Tensión al menos cada tres semanas. La alarma del sistema no se repite." to R.string.s_19bc8f2c,
    "Abrir ajustes de alarmas" to R.string.s_dc5f854f,
    "Probar alarma en 10 segundos" to R.string.s_2bcf547a,
    "Alarma de prueba programada." to R.string.s_a1e8ec34,
    "Alarma sonora además de la notificación" to R.string.s_c80eac83,
    "La alarma sonora está disponible desde iOS 26." to R.string.s_18ecbd73,
    "Configuración guardada. Permite las alarmas en Ajustes para que suenen." to R.string.s_c044241a,
    "La alarma sonora requiere iOS 26 y permiso de alarmas. Puede sonar en silencio o con Concentración, aunque la app esté cerrada. Desactívala si prefieres solo la notificación." to R.string.s_188f4d36,
    "Campo anterior" to R.string.s_3ebf14aa,
    "Campo siguiente" to R.string.s_69a94dcd,
    "Cerrar teclado" to R.string.s_2e7572a5,
    "Configuración guardada. Activa las notificaciones en Ajustes para recibir avisos." to R.string.s_33f261b,
    "Guardar aplica los cambios. Cerrar también guarda los cambios pendientes. Sin permiso de notificaciones, la configuración se conserva pero los avisos no se mostrarán." to R.string.s_6e99506c,
    "Número de tomas" to R.string.s_fc8b8ba4,
    "1 toma" to R.string.s_5596cfde,
    "3 tomas" to R.string.s_c70fa2d7,
    "Toma %ld" to R.string.s_c51cb22c,
    "Cada toma se guarda por separado. Introduce los valores de cada medición." to R.string.s_b9b19c0d,
    "Se asigna automáticamente al guardar según la hora local del iPhone: mañana antes de las 14:00 y noche desde las 14:00. Una toma guardada solo se puede eliminar." to R.string.s_474ab8c3,
    "Continuación" to R.string.s_dcae2004,
    "No se pudo leer el histórico. Se conserva el archivo original; no guardes nuevas tomas hasta recuperarlo." to R.string.s_31d56f75,
    "Sistólica (alta)" to R.string.s_70e0bf52,
    "Diastólica (baja)" to R.string.s_71b6689a,
    "Sobre la referencia" to R.string.s_657e10b6,
    "Por debajo de la referencia" to R.string.s_774e9b2c,
    "Qué significan estos valores" to R.string.s_71502458,
    "La alta (sistólica) es la presión cuando el corazón se contrae. La baja (diastólica) es la presión entre latidos; ‘baja’ no significa que el valor sea bajo." to R.string.s_adb167a4,
    "Referencia orientativa en casa para adultos: sistólica desde 135 o diastólica desde 85 mmHg. Se interpreta el promedio de varios días, no una toma aislada. Si se repite, consúltalo; no cambies tu medicación por tu cuenta. Tus objetivos pueden ser distintos. No se aplica a menores ni al embarazo." to R.string.s_6dd12efc,
    "Lectura muy elevada. Con dolor de pecho, falta de aire, debilidad o dificultad para hablar, llama a emergencias sin esperar. Sin síntomas, repite tras al menos 1 minuto y, si sigue así, contacta cuanto antes con un profesional sanitario." to R.string.s_7a8bd5e7,
    "Resumen" to R.string.s_a4a3d5c1,
    "Histórico" to R.string.s_e58f1e54,
    "Médico" to R.string.s_906797ed,
    "Guía" to R.string.s_221aa2,
    "Copia" to R.string.s_3e44d7c,
    "Guardar nueva toma" to R.string.s_42578d50,
    "Guardar" to R.string.s_790dad76,
    "Cancelar" to R.string.s_fc82e84b,
    "Nueva toma" to R.string.s_371ca486,
    "Registro individual" to R.string.s_43918486,
    "Esta toma tendrá un identificador único y se guardará en este iPhone." to R.string.s_c60c1af6,
    "Tensión arterial" to R.string.s_5d347db6,
    "Sistólica" to R.string.s_447d2917,
    "Diastólica" to R.string.s_a6d75871,
    "Momento de la toma" to R.string.s_8bf34eec,
    "Momento" to R.string.s_acd9564f,
    "Mañana" to R.string.s_892b16f7,
    "Noche" to R.string.s_47f1f1f,
    "Fecha y hora" to R.string.s_568946e0,
    "Datos opcionales" to R.string.s_378606e4,
    "Pulso" to R.string.s_49e2b83,
    "Nota para esta toma" to R.string.s_806e30c6,
    "Máximo 140 caracteres" to R.string.s_284263a5,
    "Introduce una sistólica entre 40 y 300 mmHg." to R.string.s_85510e1b,
    "La diastólica debe estar entre 30 y 200 y ser menor que la sistólica." to R.string.s_a49d2120,
    "Introduce un pulso entre 20 y 250 lpm." to R.string.s_a8611f3c,
    "No se pudo guardar la toma en este iPhone. Inténtalo de nuevo." to R.string.s_67b7b448,
    "Mis mediciones" to R.string.s_4c6b4419,
    "Guardado en este iPhone" to R.string.s_e2624268,
    "Guardada en el iPhone" to R.string.s_7ebcc62e,
    "Aún no hay tomas guardadas" to R.string.s_30bfa70a,
    "Tomas disponibles sin conexión: %ld" to R.string.s_28f0ab04,
    "ÚLTIMA TOMA" to R.string.s_f04d29d4,
    "Pulsa “Guardar nueva toma” para empezar." to R.string.s_a234b9c,
    "MEDIA 7 DÍAS" to R.string.s_f9cbd920,
    "ESTA SEMANA" to R.string.s_8a6ea3be,
    "tomas" to R.string.s_696c104,
    "EVOLUCIÓN" to R.string.s_b5a10508,
    "Últimas mediciones" to R.string.s_91079878,
    "Tu evolución aparecerá aquí" to R.string.s_1a30c3e9,
    "Guarda dos o más tomas." to R.string.s_954ebb58,
    "Registro de tomas" to R.string.s_b3ca35d2,
    "Cada tarjeta es una toma independiente" to R.string.s_d62886b3,
    "Periodo" to R.string.s_3ac3daae,
    "7 días" to R.string.s_5fce7544,
    "30 días" to R.string.s_ddba56de,
    "90 días" to R.string.s_1b1fba64,
    "Todo" to R.string.s_27dc66,
    "Todas" to R.string.s_4d3af1b,
    "Sin tomas" to R.string.s_a5aaaf9c,
    "Guarda tu primera medición." to R.string.s_d87a9c23,
    "¿Eliminar esta toma?" to R.string.s_f6cefbab,
    "Eliminar definitivamente" to R.string.s_27eecca9,
    "La toma se borrará del almacenamiento local del iPhone." to R.string.s_97f2a6d,
    "Eliminar toma" to R.string.s_dfe6134e,
    "Tomas guardadas en este iPhone: %ld" to R.string.s_612b1c06,
    "Sin tomas en este periodo" to R.string.s_cb3488e0,
    "Vista médica" to R.string.s_539710d2,
    "Mediciones" to R.string.s_ee662eb0,
    "Promedio" to R.string.s_c87dc585,
    "Sin mediciones" to R.string.s_7125c2f8,
    "No hay datos en este periodo." to R.string.s_1be0282e,
    "Compartir o imprimir" to R.string.s_d5f27807,
    "Últimos %ld días" to R.string.s_47a26b54,
    "Historial completo" to R.string.s_967d22b4,
    "lpm" to R.string.s_1a369,
    "Copia de seguridad" to R.string.s_5231ae75,
    "Guarda una copia de tus mediciones en Archivos, iCloud Drive o el servicio que prefieras." to R.string.s_d584bd65,
    "Crear y compartir copia" to R.string.s_ecdde7b9,
    "Restaurar desde una copia" to R.string.s_304f4272,
    "Contenido" to R.string.s_5f2dfd59,
    "Última copia" to R.string.s_6179e5d7,
    "La copia contiene datos de salud. Guárdala en un lugar privado y compártela solo con personas de confianza." to R.string.s_db062cc9,
    "Copia y restauración" to R.string.s_909153e3,
    "Tomas restauradas: %ld" to R.string.s_4f1d1d94,
    "No se pudo leer esta copia." to R.string.s_549e3fde,
    "Copia preparada correctamente." to R.string.s_2ce323c2,
    "No se pudo crear la copia." to R.string.s_aed0fc3,
    "Guía y privacidad" to R.string.s_db201bd4,
    "Cómo tomar la tensión" to R.string.s_b1b0cb8e,
    "Prepara el tensiómetro" to R.string.s_5f56ebdd,
    "Usa un tensiómetro validado de brazo y un manguito de tu talla. La app registra las lecturas del aparato." to R.string.s_7c829133,
    "Antes de medir" to R.string.s_5778ea1,
    "Evita ejercicio, tabaco y cafeína durante los 30 minutos previos. Vacía la vejiga." to R.string.s_d9208800,
    "Descansa 5 minutos" to R.string.s_85e87776,
    "Siéntate en silencio, con la espalda apoyada, los pies en el suelo y las piernas sin cruzar." to R.string.s_3e61eef1,
    "Coloca el brazo" to R.string.s_9ee49f60,
    "Pon el manguito sobre la piel, siguiendo las instrucciones del aparato. Apoya el brazo a la altura del corazón." to R.string.s_bce0d3dc,
    "Haz dos tomas" to R.string.s_7351154d,
    "No hables ni te muevas. Espera al menos 1 minuto entre las dos mediciones y guarda cada una por separado." to R.string.s_a38f8d7f,
    "Sigue tu pauta" to R.string.s_996169f1,
    "Mide en los horarios indicados por tu profesional sanitario y lleva el informe a la consulta." to R.string.s_7bdf6efa,
    "Fuente: American Heart Association" to R.string.s_f5d01df6,
    "Tu privacidad" to R.string.s_f3051bee,
    "No guardamos datos en servidores" to R.string.s_ea1c8dca,
    "Tus tomas y notas se guardan únicamente en el almacenamiento local de este iPhone para que puedas consultar el histórico. La app no exige una cuenta ni envía tus mediciones a nuestros servidores." to R.string.s_96f4866e,
    "Solo tú decides si exportas o compartes un informe o una copia. Las copias del dispositivo pueden incluir los datos de la app según tus ajustes de iOS." to R.string.s_3c612b37,
    "Eliminar la app puede borrar el histórico local. Exporta una copia si quieres conservarlo." to R.string.s_cfff210d,
    "Informe de seguimiento · %@" to R.string.s_8d841cb6,
    "Generado el %@" to R.string.s_818ba723,
    "Las mediciones han sido introducidas por el usuario. Este informe no sustituye la valoración clínica." to R.string.s_5ea6d1ca,
    "Fecha" to R.string.s_409d75d,
    "Serie" to R.string.s_4c1415c,
    "Alertas" to R.string.s_2c85466e,
    "Recordatorios para tus tomas" to R.string.s_139ed330,
    "Elige horarios y días para la mañana y la noche. Los avisos están desactivados inicialmente." to R.string.s_c411130e,
    "Selecciona al menos un día." to R.string.s_5cdc1c7e,
    "Activa las notificaciones en Ajustes para recibir avisos." to R.string.s_ba1a9a23,
    "Hora de tomar la tensión" to R.string.s_4c085815,
    "Descansa unos minutos y registra tu toma en Mi Tensión." to R.string.s_1c0e9bf9,
    "Guardar alertas" to R.string.s_780e21e4,
    "Alertas guardadas." to R.string.s_645478a6,
    "Abrir ajustes de notificaciones" to R.string.s_1fb58fbe,
    "Información" to R.string.s_d8b872b9,
    "Los avisos se programan en este iPhone, sin enviar datos a servidores. Funcionan aunque la app esté cerrada." to R.string.s_b8d7f7ff,
    "Debes permitir las notificaciones. El modo Concentración y los ajustes de sonido pueden silenciar o retrasar los avisos." to R.string.s_4afc7f19,
    "Son recordatorios, no alarmas médicas: no detectan valores de tensión ni sustituyen las indicaciones de tu médico." to R.string.s_469a8ee6,
    "Pulsa Guardar alertas para aplicar los cambios. Desactiva ambos avisos y guarda para cancelarlos." to R.string.s_ee47328c,
    "Cerrar" to R.string.s_781981f3,
    "Activar aviso" to R.string.s_b144c5a0,
    "Hora" to R.string.s_226996,
    "Días de la semana" to R.string.s_2d1420aa,
    "Más" to R.string.s_13cbf,
    "Gráficas" to R.string.s_e3bad0bc,
    "Tus datos, de un vistazo" to R.string.s_54ae2459,
    "Observa tus mediciones a lo largo del tiempo." to R.string.s_8df2f87e,
    "Media" to R.string.s_46c7fc4,
    "Cuida tu rutina" to R.string.s_96a4d5de,
    "Guía, avisos y tus datos, en un solo lugar." to R.string.s_691572bd,
    "Configura tus horarios y días." to R.string.s_3ee268c9,
    "Cómo medir y cómo cuidamos tus datos." to R.string.s_660a5f6,
    "Exportar a Excel" to R.string.s_e40e17fd,
    "Todas tus tomas en una hoja de cálculo." to R.string.s_f8b4e9c8,
    "Conserva y restaura tu histórico." to R.string.s_9373a6ee,
    "Notas e identificador único" to R.string.s_13bb6c38,
    "Crear archivo Excel" to R.string.s_629e024a,
    "No se pudo exportar el archivo." to R.string.s_5dc799e1,
    "Notas" to R.string.s_47f5e25,
    "Probar aviso en 10 segundos" to R.string.s_3848b42e,
    "Aviso de prueba programado." to R.string.s_541915a6,
    "Avisos programados: %ld" to R.string.s_8df6a8a9,
    "Ocultar este aviso" to R.string.s_c5861815,
    "No volverá a mostrarse en este iPhone. Tus tomas se conservan." to R.string.s_47ddbb91,
    "Medicamentos de esta toma" to R.string.s_47f2d038,
    "Registra la medicación asociada a esta medición. Es un registro, no una recomendación de tratamiento." to R.string.s_62bfb41c,
    "Nombre del medicamento" to R.string.s_954a93aa,
    "Dosis (opcional)" to R.string.s_52d3bede,
    "Nota del medicamento (opcional)" to R.string.s_9471bd41,
    "Añadir medicamento" to R.string.s_a8a355b2,
    "Quitar medicamento" to R.string.s_7ad13536,
    "Introduce el nombre del medicamento o elimina la fila vacía." to R.string.s_deeaa6fd,
    "Todavía no hay tomas" to R.string.s_52eba893,
    "Medición muy elevada" to R.string.s_5553b215,
    "Eliminar medicamento" to R.string.s_7a8aff97,
    "Revisa los valores de las tomas." to R.string.s_a5e1cd61,
    "Guardar toma" to R.string.s_28cba5b9,
    "Anterior" to R.string.s_e6d0b2d8,
    "Siguiente" to R.string.s_c3cb755f,
    "Alarma sonora" to R.string.s_e65c61dc,
    "Detener alarma" to R.string.s_54962ea7,
    "Configuración guardada" to R.string.s_c7dea4d6,
    "Permiso de alarmas exactas" to R.string.s_b2ba5380,
    "A los 30 minutos volveremos a avisarte si no has guardado la toma de ese día y periodo." to R.string.s_a4ee1fce,
    "Sin permiso de alarmas exactas, Android puede retrasar los avisos. Las alarmas sonoras necesitan ese permiso." to R.string.s_3cab47ad,
    "Las referencias son orientativas para adultos, no un diagnóstico ni un objetivo personal. No se aplican al embarazo ni a menores." to R.string.s_15a668fc
)

/** Android selects the device language; the original source key is the fallback for brand names. */
fun Context.t(key: String): String = textResources[key]?.let { getString(it) } ?: key
